sudo: required
dist: trusty
language: python
python:
- '2.7'
install: pip install -r requirements.txt

cache:
  directories:
  - /home/travis/virtualenv/python2.7/lib/python2.7/site-packages

script:
- nosetests -x -v -a \!wip
