all: zip upload

zip:
	mkdir -p build
	rm -f ./build/skill.zip
	cp -r ./lambda_function.py ./my_desk build
	find build -name "*.swp" | xargs rm -f
	echo "PROD = True # AUTOGENERATED"  > ./build/my_desk/stage.py
	cd build &&	zip -q -r skill.zip *

upload: zip
	aws lambda update-function-code --function-name MyDesk --zip-file fileb://build/skill.zip
